### ISSUE TITLE
heat_param config not documented

### ISSUE THREAD

**Issue by izaakk** [osic/ops-workload-framework#2]
We should specify the user that he needs to specify the resource location (Maybe we could use relative paths and designate the specific folder for resource definition)
Let's not hardcode the image_id or Network_id

Maybe we should automate this, every single resource may have different needs, image for example.

**Comment by shashank0791** [comment]
Yeah..good idea...we can actually provide an option inside python wrapper to provide location of the resource definition. 
We can create resource specific variables and then try to automate some of them as much as we can so each resource will have their specific images/network/flavor.
Automating can also be done where we can just prompt the user to enter an image name/ network type/ flavor. This can be done through the wrapper. 
 I will document the existing config in the md file.

**Comment by shashank0791** [comment]
Changes have been made in branch: v1.1
